#!/command/with-contenv /usr/bin/bash
# shellcheck shell=bash

# make db config folder
mkdir -p "$PGDATA" "/config/logs/postgres"

# permissions
chown postgres:postgres -R "$PGDATA" "/config/logs/postgres"
chmod 700 -R "$PGDATA"
chmod 755 -R "/config/logs/postgres"

exec postgres-entrypoint.sh postgres -c log_directory="/config/logs/postgres" -c log_rotation_size=10MB