#!/command/with-contenv bash
# shellcheck shell=bash

s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 3000" s6-setuidgid gotenberg gotenberg --chromium-disable-javascript=true --chromium-allow-list="file:///tmp/.*"