#!/command/with-contenv bash
# shellcheck shell=bash

set -e

# ------------------------------------------------------------------------
# Dashboard managed
# ------------------------------------------------------------------------

if [ -n "$TOKEN" ]; then
  cloudflared tunnel --no-autoupdate run --token "$TOKEN"
  exit 0
fi

# ------------------------------------------------------------------------
# Locally managed
# ------------------------------------------------------------------------

# Cloudflare credentials
CLOUDFLARE_CREDENTIALS="/config/cert.pem"

if [ ! -f "$CLOUDFLARE_CREDENTIALS" ]; then
  cloudflared --no-autoupdate tunnel login

  mv /root/.cloudflared/* /config/

  if [ ! -f "$CLOUDFLARE_CREDENTIALS" ]; then
    echo "Login error"
    exit 1
  fi
fi

# Tunnel creation

TUNNEL_CONFIG="/config/tunnel.json"

if [ ! -f "$TUNNEL_CONFIG" ]; then
  cloudflared --no-autoupdate tunnel --origincert "$CLOUDFLARE_CREDENTIALS" --credentials-file "$TUNNEL_CONFIG" create "$TUNNEL_NAME"

  if [ -f "$TUNNEL_CONFIG" ]; then
    echo "$TUNNEL_NAME tunnel created"
  else
    echo "Could not create tunnel"
    exit 1
  fi
fi

# Cloudflared config

CLOUDFLARED_CONFIG=/config/config.yml

# Initializie config if not present
if [ ! -f "$CLOUDFLARED_CONFIG" ]; then
  tunnel_id="$(jq -r '.TunnelID' "$TUNNEL_CONFIG")"

  if [ -n "$tunnel_id" ]; then
    yq -n "
      .tunnel = \"$tunnel_id\" |
      .credentials-file = \"$TUNNEL_CONFIG\"
    " > "$CLOUDFLARED_CONFIG"
  else
    echo "Unable to find TunnelID in $TUNNEL_CONFIG"
    exit 1
  fi
fi

# Load configuration from the addon config

OPTIONS_SOURCE=/data/options.json

yq eval -i "
  .warp-routing.enabled = load(\"$OPTIONS_SOURCE\").warp-routing |
  .originRequest = load(\"$OPTIONS_SOURCE\").originRequest |
  .ingress = load(\"$OPTIONS_SOURCE\").ingress
" "$CLOUDFLARED_CONFIG"

# Add network routings
jq -r '.network_routings[]' "$OPTIONS_SOURCE" | while read -r network_routing; do
  echo "Adding route for: $network_routing"
  cloudflared --no-autoupdate tunnel --config "$CLOUDFLARED_CONFIG" --origincert "$CLOUDFLARE_CREDENTIALS" --credentials-file "$TUNNEL_CONFIG" route ip add "$network_routing" "$TUNNEL_NAME" || true
done

cloudflared --no-autoupdate tunnel --config "$CLOUDFLARED_CONFIG" --origincert "$CLOUDFLARE_CREDENTIALS" --credentials-file "$TUNNEL_CONFIG" run