#!/command/with-contenv /usr/bin/bash
set -e

[[ -d "/config/logs" ]] && mv /config/logs /data/logs

echo "  Loading env variables:"

OPTIONS_SOURCE=/data/options.json

jq -r 'keys[]' "${OPTIONS_SOURCE}" | while read -r KEY; do
    # export key
    value=$(jq -r --arg key "$KEY" '.[$key]' "${OPTIONS_SOURCE}")

    # Continue for single values
    line="${KEY}=${value}"

    # log redacted config
    case "$KEY" in
        *PASS*|*SECRET*|*KEY*)
            echo "    ${KEY}=******"
            ;;
        *)
            echo "    $line"
            ;;
    esac

    export "$line"

    # set .env
    echo "$line" >> /.env || true

    # set /etc/environment
    echo "$line" >> /etc/environment

    # For s6
    if [ -d /var/run/s6/container_environment ]; then
        printf "%s" "$value" > /var/run/s6/container_environment/"${KEY}"
    fi
    echo "export $line" >> ~/.bashrc
done

if [ -n "$PAPERLESS_TIME_ZONE" ] && [ -f /etc/localtime ]; then
    if [ -f /usr/share/zoneinfo/"$PAPERLESS_TIME_ZONE" ]; then
        echo "Timezone set from $(cat /etc/timezone) to $PAPERLESS_TIME_ZONE"
        ln -snf /usr/share/zoneinfo/"$PAPERLESS_TIME_ZONE" /etc/localtime
        echo "$PAPERLESS_TIME_ZONE" >/etc/timezone
    fi
fi
