#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ "${#MYSQL_ROOT_PASSWORD}" -gt "3" ]]; then
    # display a message about upgrading database if needed
    if mariadb-upgrade -u root -p"${MYSQL_ROOT_PASSWORD}" --check-if-upgrade-is-needed >/dev/null 2>&1; then
        echo "Upgrading MariaDB, this could take some time!"
        echo "Don't stop the add-on!"
        if ! mariadb-upgrade -u root -p"${MYSQL_ROOT_PASSWORD}"; then
            echo "Error: MariaDB upgrade failed!" >&2
            exit 1
        fi
    fi
fi
