name: OpenSpeedTest
version: 2.0.6
slug: openspeedtest
description: SpeedTest by OpenSpeedTest™ is a Free and Open-Source HTML5 Network Performance Estimation Tool Written in Vanilla Javascript
url: https://openspeedtest.com
ingress: true
panel_icon: mdi:speedometer
panel_admin: false
ingress_port: 3000
ingress_stream: true
arch:
  - i386
  - aarch64
  - armv7
  - amd64
init: false
ports:
  3000/tcp:
ports_description:
  3000/tcp: HTTP (Not required for Ingress)
image: openspeedtest/latest
