#!/command/with-contenv bash
# shellcheck shell=bash

set -e

echo "  Loading env variables:"

OPTIONS_SOURCE=/data/options.json

if [[ ! -f "$OPTIONS_SOURCE" ]]: then
    echo "Options file doesn't exist!"
    exit 2
fi

while IFS="=" read -r key val; do

    key=$(echo "$key" | tr '[:lower:]' '[:upper:]' | sed 's/[^A-Z0-9_]/_/g')

    # Redact log
    case "$key" in
        *PASS*|*SECRET*|*KEY*|*TOKEN*)
            echo "  ${key}=******"
            ;;
        *)
            echo "  $line"
            ;;
    esac

    local env=$key\="$value"

    export $env

    # set .env
    echo "$env" >> ~/.env || true
    
    # add env to .bashrc
    echo "export $line" >> ~/.bashrc

    # set /etc/environment
    echo "$env" >> /etc/environment

    # set s6 environment variables
    if [ -d /var/run/s6/container_environment ]; then
        printf "%s" "$value" > /var/run/s6/container_environment/"$key"
    fi
done < <(
    jq -r '
        to_entries[]
        | if .key == "env_vars" then
            .value[]?
          elif (.value | type) == "object" then
            .value | to_entries[]
          end
        | select(.value | type != "object" and type != "array")
        | "\(.key)=\(.value|tostring)"
    ' "$OPTIONS_SOURCE"
)

if [ -n "$TZ" ] && [ -f "/usr/share/zoneinfo/$TZ" ]; then
    if [ -f /usr/share/zoneinfo/"$TZ" ]; then
        echo "Timezone set to $TZ"
        ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime
        echo "$TZ" >/etc/timezone
    fi
fi
