#!/command/with-contenv bash
# shellcheck shell=bash

set -e

[[ ! -d "/config/runner" ]] && mkdir -p "/config/runner"

#chown -R 1000:1000 /config/runner

exec /usr/local/bin/task-runner-launcher javascript python
