#!/command/with-contenv bash
# shellcheck shell=bash

# make redis folders
mkdir -p \
	"$REDIS_DATADIR" \
	/data/logs \
	/var/run/redis

# copy redis defaults
[[ ! -f "$REDIS_DATADIR/redis.conf" ]] &&
	cp /defaults/redis.conf "$REDIS_DATADIR/redis.conf"

if jq -e '.clean_redis == true' $OPTIONS_SOURCE > /dev/null; then
	rm -f "$REDIS_DATADIR/dump.rdd"
fi

s6-notifyoncheck -s 1000 -n 300 -w 1000 -c "redis-cli PING" \
	redis-server "$REDIS_DATADIR/redis.conf" \
		--bind 0.0.0.0 \
		--port 6379 \
		--pidfile /var/run/redis/redis.pid \
		--always-show-logo no \
		--dir "$REDIS_DATADIR" \
		--daemonize no \
		--logfile /data/logs/redis.log \
		--unixsocket /var/run/redis/redis.sock \
		--unixsocketperm 777