# check=skip=SecretsUsedInArgOrEnv
ARG BUILD_FROM=ghcr.io/bookorbit/bookorbit:2.7.0

FROM ${BUILD_FROM}

# Environment variables
ENV \
    PORT=3000 \
    APP_PORT=3000 \
    NODE_MAX_OLD_SPACE_SIZE="auto"

# hadolint ignore=DL3064
ENV \
    SETUP_BOOTSTRAP_TOKEN=bookorbit \
    PG_MAJOR=18 \
    PGDATA="/config/postgres" \
    POSTGRES_INITDB_ARGS="--data-checksum" \
    POSTGRES_DB="bookorbit" \
    POSTGRES_USER="bookorbit" \
    POSTGRES_PASSWORD="bookorbit" \
    POSTGRES_SEARCH_PATH="postgres, public, vectors" \
    DATABASE_URL="postgresql:///bookorbit?host=/var/run/postgresql&user=bookorbit&password=bookorbit"

ENV \
    SERVICE_PORT=3000 \
    NGINX_PORT=8080

# NGINX Install
RUN \
    apk add --no-cache \
        bash \
        openssl \
        nginx \
    && rm -rf /etc/nginx

# Shell
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# Addon base configuration
ARG BUILD_ARCH=amd64
# renovate: datasource=github-releases packageName=hassio-addons/bashio
ARG BASHIO_VERSION="v0.18.1"
# renovate: datasource=github-releases packageName=just-containers/s6-overlay versioning=regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)\.(?<other>\d+)$
ARG S6_OVERLAY_VERSION="3.2.1.0"
# renovate: datasource=github-releases packageName=home-assistant/tempio
ARG TEMPIO_VERSION="2024.11.2"
RUN \
    apk add --no-cache --virtual .build-dependencies \
        tar \
        xz \
    \
    && apk add --no-cache \
        libcrypto3 \
        libssl3 \
        musl-utils \
        musl \
        bash \
        curl \
        jq \
        tzdata \
    \
    && S6_ARCH="${BUILD_ARCH}" \
    && if [ "${BUILD_ARCH}" = "amd64" ]; then S6_ARCH="x86_64"; fi \
    \
    && curl -L -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-noarch.tar.xz" \
        | tar -C / -Jxpf - \
    \
    && curl -L -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-${S6_ARCH}.tar.xz" \
        | tar -C / -Jxpf - \
    \
    && curl -L -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-noarch.tar.xz" \
        | tar -C / -Jxpf - \
    \
    && curl -L -s "https://github.com/just-containers/s6-overlay/releases/download/v${S6_OVERLAY_VERSION}/s6-overlay-symlinks-arch.tar.xz" \
        | tar -C / -Jxpf - \
    \
    && curl -J -L -o /tmp/bashio.tar.gz \
        "https://github.com/hassio-addons/bashio/archive/${BASHIO_VERSION}.tar.gz" \
    && mkdir /tmp/bashio \
    && tar zxvf \
        /tmp/bashio.tar.gz \
        --strip 1 -C /tmp/bashio \
    \
    && mv /tmp/bashio/lib /usr/lib/bashio \
    && ln -s /usr/lib/bashio/bashio /usr/bin/bashio \
    \
    && curl -L -s -o /usr/bin/tempio \
        "https://github.com/home-assistant/tempio/releases/download/${TEMPIO_VERSION}/tempio_${BUILD_ARCH}" \
    && chmod a+x /usr/bin/tempio \
    \
    && apk del --no-cache --purge .build-dependencies \
    && rm -f -r \
        /tmp/*

RUN apk add --no-cache bash logrotate postgresql${PG_MAJOR} postgresql${PG_MAJOR}-client postgresql${PG_MAJOR}-contrib postgresql-common; \
#    groupadd -r -g 900 postgres; \
#    useradd -r -u 900 -g postgres --home-dir=/var/lib/postgresql --shell=/bin/bash postgres; \
	install --verbose --directory --owner postgres --group postgres --mode 1777 /var/lib/postgresql; \
    install --verbose --directory --owner postgres --group postgres --mode 3777 /var/run/postgresql; \
    mkdir /docker-entrypoint-initdb.d; \
    postgres --version

# renovate: datasource=github-tags packageName=pgvector/pgvector
ARG PGVECTOR_VERSION="v0.8.6"

ADD https://github.com/pgvector/pgvector.git#${PGVECTOR_VERSION} /tmp/pgvector

RUN apk add --no-cache --virtual .build-deps \
        build-base \
        linux-headers \
        postgresql${PG_MAJOR}-dev \
    && cd /tmp/pgvector \
    && make clean \
    && make OPTFLAGS="" \
    && make install \
    && mkdir -p /usr/share/doc/pgvector \
    && cp LICENSE README.md /usr/share/doc/pgvector \
    && rm -rf /tmp/pgvector \
    && apk del .build-deps

COPY .common/addon-config /
COPY .common/postgres/etc/postgresql/postgresql.hdd.conf /etc/postgresql/
COPY .common/postgres/etc/postgresql/postgresql.ssd.conf /etc/postgresql/
COPY .common/postgres/etc/s6-overlay /etc/s6-overlay/
COPY .common/postgres/usr/local/bin /usr/local/bin/
COPY .common/nginx /

COPY rootfs/ /

ENTRYPOINT ["/init"]

ARG BUILD_VERSION \
    BUILD_DATE \
    BUILD_DESCRIPTION \
    BUILD_NAME \
    BUILD_REF \
    BUILD_REPOSITORY

LABEL \
    io.hass.name="${BUILD_NAME}" \
    io.hass.description="${BUILD_DESCRIPTION}" \
    io.hass.arch="${BUILD_ARCH}" \
    io.hass.type="addon" \
    io.hass.version="${BUILD_VERSION}" \
    maintainer="Fabio Garavini <info@fabiogaravini.dev>" \
    org.opencontainers.image.title="${BUILD_NAME}" \
    org.opencontainers.image.description="${BUILD_DESCRIPTION}" \
    org.opencontainers.image.vendor="Fabio Garavini Hassio Add-ons" \
    org.opencontainers.image.authors="Fabio Garavini <info@fabiogaravini.dev>" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.url="https://github.com/fabio-garavini" \
    org.opencontainers.image.source="https://github.com/${BUILD_REPOSITORY}" \
    org.opencontainers.image.documentation="https://github.com/${BUILD_REPOSITORY}/blob/main/README.md" \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.revision=${BUILD_REF} \
    org.opencontainers.image.version=${BUILD_VERSION}
