#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p \
    "${MACHINE_LEARNING_CACHE_FOLDER}" \
    "${IMMICH_MEDIA_LOCATION}/library"

# permissions
find /app/immich -path "*/node_modules" -prune -o -exec chown abc:abc {} +
chown -R abc:abc \
    "${MACHINE_LEARNING_CACHE_FOLDER}"
chown abc:abc \
    "${IMMICH_MEDIA_LOCATION}" \
    "${IMMICH_MEDIA_LOCATION}"/*

lsiown -R abc:abc "${IMMICH_MEDIA_LOCATION}"