name: Frigate RKNN (Rockchip)
version: 0.16.2-rk
panel_icon: mdi:cctv
panel_title: Frigate
slug: frigate_rk
description: NVR with realtime local object detection for IP cameras
url: https://github.com/blakeblackshear/frigate
image: ghcr.io/blakeblackshear/frigate
init: false
ingress: true
ingress_port: 5000
ingress_entry: /
panel_admin: false
homeassistant_api: true
hassio_api: true
ports:
  8555/tcp: 8555
  8555/udp: 8555
  8554/tcp:
  8971/tcp:
  5000/tcp:
  1984/tcp:
  1935/tcp:
ports_description:
  8555/tcp: WebRTC over tcp
  8555/udp: WebRTC over udp
  8554/tcp: RTSP Restream
  8971/tcp: Authenticated Web interface
  5000/tcp: Unauthenticated Web interface (Not required for Hass.io Ingress)
  1984/tcp: go2rtc API
  1935/tcp: RTMP streams
devices:
  - /dev/dri/renderD128
  - /dev/dri/renderD129
  - /dev/dri/card0
  - /dev/kfd
  - /dev/apex_0
  - /dev/apex_1
  - /dev/apex_2
  - /dev/apex_3
  - /dev/vchiq
  - /dev/video10
  - /dev/video0
  - /dev/hailo0
  - /dev/hailo1
usb: true
video: true
tmpfs: true
privileged:
  - PERFMON
environment:
  CONFIG_FILE: /config/frigate.yml
schema:
  plus_api_key: password?
services:
  - mqtt:want
arch:
  - aarch64
map:
  - type: media
    read_only: false
  - type: addon_config
    read_only: false
  - type: homeassistant_config
    read_only: false
  - type: ssl
