#!/command/with-contenv /usr/bin/bash
set -e

mkdir -p ${PGDATA}-backups
chown postgres:postgres -R ${PGDATA}-backups

if [ -d "${PGDATA}-15-backup" ]; then
    mv $PGDATA "${PGDATA}-backups/$(date +"%Y-%m-%d_%H-%M-%S")"
    mv "${PGDATA}-15-backup" $PGDATA
fi

if [ -f "$PGDATA/PG_VERSION" ] && ! grep -q "$PG_MAJOR" "$PGDATA/PG_VERSION"; then

    current_pg_major=$(cat "$PGDATA/PG_VERSION" | cut -d '.' -f 1)

    echo "Postgres $current_pg_major needs an upgrade"

    mv $PGDATA ${PGDATA}-migrate

    source postgres-entrypoint.sh

    docker_setup_env

    docker_create_db_directories

    gosu postgres bash -c "
        source postgres-entrypoint.sh

        docker_setup_env
        
        docker_init_database_dir
    "

    apt-get update
    apt-get install -y postgresql-${current_pg_major}

    cd $PGDATA

    su postgres -c '/usr/lib/postgresql/16/bin/pg_upgrade --copy -d '"${PGDATA}-migrate"' -D '"$PGDATA"' -b '"/usr/lib/postgresql/$current_pg_major/bin"' -B '"/usr/lib/postgresql/$PG_MAJOR/bin"' --username="$POSTGRES_USER"'

    apt-get remove -y postgresql-${current_pg_major}
    apt autoremove -y
    apt autoclean -y

    mv "${PGDATA}-migrate" "${PGDATA}-backups/$(date +"%Y-%m-%d_%H-%M-%S")"
fi
