name: Grist
version: 1.7.4-v1
slug: grist
codenotary: info@fabiogaravini.dev
description: A modern, open-source spreadsheet software that goes beyond the grid
url: https://www.getgrist.com
webui: "[PROTO:ssl]://[HOST]:[PORT:8080]/o/docs/"
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: false
    path: /persist
  - type: ssl
backup: cold
backup_exclude:
  - "**/cache"
  - "**/logs"
schema:
  TZ: str?
  ssl: bool
  certfile: str?
  keyfile: str?
  GRIST_SESSION_SECRET: str
  GRIST_DEFAULT_EMAIL: str
  APP_HOME_URL: str?
  APP_DOC_URL: str?
  GRIST_SINGLE_ORG: str?
  GRIST_ANON_PLAYGROUND: bool?
  GRIST_FORCE_LOGIN: bool?
options:
  TZ: Etc/UTC
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  GRIST_SESSION_SECRET: invent-a-secret-here
  GRIST_DEFAULT_EMAIL: example@mail.com
ports:
  8080/tcp: 8484
ports_description:
  8080/tcp: Grist
image: fabioogaravini/hassio-grist
