#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders if required
mkdir -p \
    ${MARIADB_DATADIR} \
	/config/logs/mariadb \
    /var/run/mysqld

# set permissions
chmod -R 777 /var/run/mysqld

chown -R abc:abc \
    ${MARIADB_DATADIR} \
	/config/logs/mariadb \
    /var/run/mysqld
