name: Grocy
version: 4.5.0-v5
slug: grocy
codenotary: info@fabiogaravini.dev
description: groceries & household management solution for your home
url: https://grocy.info
webui: https://[HOST]:[PORT:443]
arch:
  - aarch64
  - amd64
init: false
map:
  - type: addon_config
    read_only: false
  - type: ssl
backup: cold
backup_exclude:
  - "**/cache"
  - "**/logs"
schema:
  TZ: str?
  certfile: str?
  keyfile: str?
options:
  TZ: Etc/UTC
  certfile: fullchain.pem
  keyfile: privkey.pem
ports:
  443/tcp: 9283
ports_description:
  443/tcp: Grocy
image: fabioogaravini/hassio-grocy
