build_from:
  aarch64: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.3.0
  amd64: ghcr.io/immich-app/postgres:16-vectorchord0.3.0-pgvectors0.3.0
codenotary:
  signer: info@fabiogaravini.dev
