#!/usr/bin/with-contenv bash

# make db config folder
mkdir -p "$PGDATA" "/config/logs/postgres"

# copy defaults
[[ ! -f ${PGDATA}/postgresql.conf ]] &&
	cp /defaults/postgresql.conf ${PGDATA}/postgresql.conf

# permissions
chown postgres:postgres -R "$PGDATA" "/config/logs/postgres"
chmod 755 -R "$PGDATA" "/config/logs/postgres"

exec s6-setuidgid postgres postgres-entrypoint.sh postgres -c shared_preload_libraries=vectors.so -c search_path=postgres,public,vectors -c log_directory="/config/logs/postgres" -c log_rotation_size=10MB