#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ -f /config/app.db ]; then
    sqlite3 /config/app.db 'update settings set config_reverse_proxy_login_header_name="X-WebAuth-User",config_allow_reverse_proxy_header_login=1'
else
    bashio::log.error "unable to find /config/app.db"
fi