#!/command/with-contenv bash
# shellcheck shell=bash

set -e

OPTIONS_SOURCE=/data/options.json

if jq -e '.tunnel == true' $OPTIONS_SOURCE > /dev/null; then
    exec n8n start --tunnel
else
    exec n8n start
fi
