#!/command/with-contenv bash
# shellcheck shell=bash

set -e

if [ ! -d "/data/cache" ]; then
  mkdir -p "/data/cache"
  chown -R chrome:chrome /data/cache
fi

cd /usr/src/chrome

su chrome -c "chromium-browser --headless --no-sandbox --disable-gpu --disable-dev-shm-usage --remote-debugging-address=0.0.0.0 --remote-debugging-port=9222 --hide-scrollbars --disable-crash-reporter --no-crash-upload &> /dev/null"