---
name: Redis DB
version: 7.4.0-v6
slug: redis
codenotary: info@fabiogaravini.dev
description: Redis database
url: https://redis.io
startup: initialize
arch:
  - aarch64
  - amd64
init: false
backup: cold
map:
  - type: addon_config
    read_only: false
ports:
  6379/tcp:
  8001/tcp:
  9121/tcp:
ports_description:
  6379/tcp: Database
  8001/tcp: Redis Insight
  9121/tcp: Redis Exporter
image: fabioogaravini/hassio-redis-stack
