---
name: Renovate

on:
  schedule:
    - cron: 0 3 * * *
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.14
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          docker-volumes: |
            /tmp:/tmp
        env:
          RENOVATE_PLATFORM_COMMIT: 'true'
          RENOVATE_EXPOSE_ALL_ENV: 'true'
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ALLOWED_COMMANDS: .*
          LOG_LEVEL: debug
